language: c
compiler: clang
script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make test test-all-sizes-ci DISABLE_ASSERTS="" COVERAGE=1 ; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "L7U9+2GkKWXMw4i3kQ1oDa8Kr7rEXQNkZG0zMbNUPCqZdZJxeNpypi9wtoGHDOJ7h1Caxztcd/wUKUgoTqEAku4h8gNidRIF1NaRqvA3oAxHNFqetoSOie0DB5t+45/rpi16Q6vfVPeiqDyh80PpYq8iTRhznx7KqzNGbVcwivM="

#after_success:
#   - bash <(curl -s https://codecov.io/bash)
addons:
    apt:
        packages:
            - libpcre3-dev
    coverity_scan:
        project:
            name: "DavyLandman/csvtools"
            description: "CSV tools"
        notification_email: davy.landman@gmail.com
        #build_command_prepend: "<Your build preprocessing command here>"
        build_command:   "make all"
        branch_pattern: coverity_scan
