language: c
compiler: clang

addons:
  apt:
     packages:
         - libpcre3-dev
  sonarcloud:
      organization: "davylandman-github"

script:
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then build-wrapper-linux-x86-64 --out-dir output make test test-all-sizes-ci DISABLE_ASSERTS="" COVERAGE=1; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then make test test-all-sizes-ci DISABLE_ASSERTS="" COVERAGE=1; fi'

after_success:
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner -Dsonar.sources=. -Dsonar.projectKey="DavyLandman_csvtools" -Dsonar.cfamily.build-wrapper-output=output; fi'
