language: c
compiler: clang

addons:
  apt:
     packages:
         - libpcre3-dev
  sonarcloud:
      organization: "davylandman-github"

script:
   - build-wrapper-linux-x86-64 --out-dir output make test test-all-sizes-ci DISABLE_ASSERTS="" COVERAGE=1

after_success:
   - sonar-scanner -Dsonar.sources=. -Dsonar.projectKey="DavyLandman_csvtools" -Dsonar.cfamily.build-wrapper-output=output
